import random, datetime, os

now  = datetime.datetime.now()
hour = now.hour

time_states = {
    (0,6):   ["deep scan in progress","network dark","ghost mode: ON","sleeping process detected"],
    (6,12):  ["booting identity matrix","signal weak","morning recon","system warming up"],
    (12,18): ["observer active","tracking enabled","background process running","surveillance mode"],
    (18,24): ["unknown entity detected","signal unstable","evening crawl","data harvesting"],
}
status = "standby"
for (s,e), opts in time_states.items():
    if s <= hour < e:
        status = random.choice(opts)
        break

locations = [
    "somewhere between packets",
    "node 127.0.0.1 loopback",
    "behind seven proxies",
    "coordinates: [REDACTED]",
    "/dev/null",
    "your blind spot",
    "subnet 255.255.255.0",
]
quotes = [
    '"Hello, friend."',
    '"Control is an illusion."',
    '"Is any of it real?"',
    '"I am not the good guy."',
    '"Every hacker has a specific MO."',
    '"People do not see what they choose not to see."',
    '"Give a man a bank and he can rob the world."',
]

def bar(pct):
    f = int(pct/10)
    return "█"*f + "░"*(10-f)

skills = {
    "social engineering": random.randint(60,99),
    "network recon":      random.randint(70,99),
    "staying invisible":  random.randint(80,99),
    "trust no one":       random.randint(85,99),
    "python":             random.randint(75,99),
    "existential dread":  random.randint(90,100),
}
skill_block = "\n".join(f"  {k:<22} {bar(v)}  {v}%" for k,v in skills.items())

moods = [
    ("▓▓▓▓▓░░░░░","paranoid"), ("▓▓▓░░░░░░░","suspicious"),
    ("▓▓▓▓▓▓▓░░░","focused"),  ("▓▓▓▓▓▓▓▓░░","deep in it"),
    ("▓▓▓▓▓▓▓▓▓▓","in the zone"), ("▓░░░░░░░░░","distracted"),
]
mood_bar, mood_label = random.choice(moods)

logs = [
    f"[{now.strftime('%H:%M:%S')}] INIT  process {random.randint(1000,9999)} attached",
    f"[{now.strftime('%H:%M:%S')}] SCAN  {random.randint(1,254)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)} found",
    f"[{now.strftime('%H:%M:%S')}] WARN  {random.choice(['anomaly detected','signal noise +12dB','unknown handshake','packet loss 0.3%'])}",
    f"[{now.strftime('%H:%M:%S')}] INFO  uptime {random.randint(1,999)}h {random.randint(0,59)}m",
    f"[{now.strftime('%H:%M:%S')}] EXEC  module {random.choice(['shadow.py','recon.sh','nullify.c','trace.go'])} loaded",
]
random.shuffle(logs)

ts       = now.strftime("%Y-%m-%d %H:%M")
quote    = random.choice(quotes)
location = random.choice(locations)

content = f"""<!--  auto-generated by observer system. do not edit manually. -->

<div align="center">

```
  +------------------------------------------------------+
  |                                                      |
  |        M O M O R U 1 9   O B S E R V E R            |
  |                                                      |
  |   status  :  {status:<37}|
  |   updated :  {ts:<37}|
  |   origin  :  {location:<37}|
  |                                                      |
  +------------------------------------------------------+
```

</div>

---

```
$ tail -f /var/log/momoru.log
{logs[0]}
{logs[1]}
{logs[2]}
{logs[3]}
{logs[4]}
```

---

<div align="center">

> {quote}

</div>

---

```
 SKILL MATRIX
 -----------------------------------------------
{skill_block}
```

---

```yaml
operator:
  alias     : momoru19
  role      : unknown
  clearance : CLASSIFIED
  os        : does not matter, i own it
  mood      : {mood_bar} {mood_label}
```

---

<div align="center">

![Python](https://img.shields.io/badge/Python-0d1117?style=for-the-badge&logo=python&logoColor=3776AB)
![Bash](https://img.shields.io/badge/Bash-0d1117?style=for-the-badge&logo=gnu-bash&logoColor=4EAA25)
![Linux](https://img.shields.io/badge/Linux-0d1117?style=for-the-badge&logo=linux&logoColor=FCC624)
![Docker](https://img.shields.io/badge/Docker-0d1117?style=for-the-badge&logo=docker&logoColor=2496ED)
![Neovim](https://img.shields.io/badge/Neovim-0d1117?style=for-the-badge&logo=neovim&logoColor=57A143)

</div>

---

<div align="center">

```
  do not look for me.
  if you are here, i already know.
```

![](https://komarev.com/ghpvc/?username=Momoru19&color=0d1117&style=flat-square&label=observer)

</div>

<sub align="right">last signal: {ts} · auto-updated every 30 min</sub>
"""

with open("README.md", "w", newline="\n", encoding="utf-8") as f:
    f.write(content)
print("  [+] README.md OK")
